config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  devise_for :users
  devise_for :installs
  
  resources :users
  
  resources :cars do
    resources :rents
  end
  
  root 'static_pages#home'
  

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :user
  has_many :rents, dependent: :destroy
  
  validates :name, :about, :comfort, :presence => true
  validates :name, length: {minimum: 3}

end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/price.rb
class Price < ActiveRecord::Base
end

app/models/rent.rb
class Rent < ActiveRecord::Base
  belongs_to :car
  validates :from_date, :to_date, :presence => true
  before_validation :available, :on => :create
  
  validates :client, length: {minimum: 3}, :presence => true
  validates_datetime :from_date, :on => :create, :on_or_after => :now
  validates_datetime :to_date, :on => :create, :after => :from_date


  def available
    @car = Car.find(self.car_id)
    rented = @car.rents.where("(from_date <= :from_date and to_date >= :from_date) or (from_date <= :to_date and to_date >= :to_date)",
                                      {:from_date => self.from_date, :to_date => self.to_date}).count
    
    return(rented == 0)
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  
  before_action :authenticate_user!, except:[:index, :show]
  
  def index
    @cars = Car.all
  end
  
  def show
    @car = Car.find(params[:id])
  end
  
  def new
    @car = current_user.cars.build
  end
  
  def create
    @car = current_user.cars.build(cars_params)
    
    if @car.save
      redirect_to cars_path
      flash[:success] = "New car added!"
    else
      render "new"
    end
  end
  
  def edit
    @car = Car.find(params[:id])
  end
  
  def update
    @car = Car.find(params[:id])
    
    if @car.update_attributes(cars_params)
      redirect_to cars_path
      flash[:success] = "Car updated!"
      #:notice => "Car updated"
    else
      render "edit"
    end
  end
  
  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to cars_path
    flash[:success] = "Car deleted!"
  end
  
    private 
  
    def cars_params
      params.require(:car).permit(:name, :about, :comfort)
    end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  def create
    @car = Car.find(params[:car_id])
    @rent = @car.rents.create(rent_params)
    
    if @car.save
      redirect_to car_path(@car), :notice => "Rent created"
    else
       redirect_to car_path(@car), :notice => "Wrong rent data"
    end
    
  end
  
  def destroy
    @car = Car.find(params[:car_id])
    @rent = @car.rents.find(params[:id])
    @rent.destroy
    redirect_to car_path(@car)
    flash[:success] = "Rent destroyed"
  end
 
  private
    def rent_params
      params.require(:rent).permit(:client, :from_date, :to_date)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      redirect_to cars_path
    end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  #def destroy
    #super
  #end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/cars/edit.html.erb
<% provide(:title, "Edit car") %>

<h3>Edit car</h3>

<%= form_for @car do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :about %><br />
    <%= f.text_area :about %>
  </p>
  <p>
    <%= f.label :comfort %>
    <%= f.radio_button :comfort, 'A', :checked => true %>A
    <%= f.radio_button :comfort, 'B' %>B
    <%= f.radio_button :comfort, 'C' %>C
    
  </p>
  <p>
   <%= f.submit "Edit car",  class: "btn btn-success" %>
    
  </p>
<% end %>

app/views/cars/index.html.erb
<% provide(:title, "Cars") %>

<h3> Cars </h3>

<% @cars.each do |car| %>

  <p><%= link_to car.name, car %></p>
  <p><%= car.about %></p>
  <p>Klasa: <%= car.comfort %></p>
  <p>
    <%= link_to "Edit", edit_car_path(car) %> |
    <%= link_to "Delete", car, :method => :delete, :confirm => "Are you sure?" %>
  </p>
  <hr />
  
 
<% end %>

<p><%= link_to "Add new car", new_car_path, class: "btn btn-success" %></p>

app/views/cars/new.html.erb
<% provide(:title, "New car") %>

<h3>Add a new car</h3>

<%= form_for @car do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :about %><br />
    <%= f.text_area :about %>
  </p>
  <p>
    <%= f.label :comfort %>
    <%= f.radio_button :comfort, 'A', :checked => true %>A
    <%= f.radio_button :comfort, 'B' %>B
    <%= f.radio_button :comfort, 'C' %>C
    
  </p>
  <p>
   <%= f.submit "Add car",  class: "btn btn-success" %>
    
  </p>
<% end %>

app/views/cars/show.html.erb
<% provide(:title, @car.name) %>

<div class="row">
  <aside class="col-md-8">
    <section>  
  
          <h1><%= @car.name %></h1>
          <p><%= @car.about %></p>
          <p>Klasa: <%= @car.comfort %> | 
          Day fare: <%= Price.where("comfort = ?", @car.comfort).uniq.pluck(:fare)[0] %> zł</p>
          <p>
              <%= link_to "Edit", edit_car_path(@car) %>
          </p>
          <hr />
   </section>
   <section>
      <h2>Rents</h2>
      <%= render @car.rents %>
   </section> 
  </aside>
  
  <div class="col-md-4">
      <h2>Add a reservation:</h2>
      <%= render 'rents/form' %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Car Rental Application</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top navbar-inverse">
  <div class ="container">
    <h1 class = "logo" >Car rental support application</h1>
    <nav>
       <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path, class: "btn btn-success" %></li>
        <% if user_signed_in? %>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-success" %></li>
        <% end %>
      </ul>
    </nav>
  </div>  
</div>
  
<div class="center jumbotron">
  
  <% flash.each do |key,value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
  <%= yield %>
  <%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>

app/views/rents/_form.html.erb
<%= form_for([@car, @car.rents.build]) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <p>
          <%= f.label :client %><br>
          <%= f.text_field :client %>
        </p>
        <p>
          <%= f.label "Rent date" %><br>
          <%= f.date_select :from_date, :start_year => 2015 %>
        </p>
        <p>
          <%= f.label "Return date" %><br>
          <%= f.date_select :to_date, :start_year => 2015 %>
        </p>
        <p>
          <%= f.submit "New rent`",  class: "btn btn-success" %>
        </p>
<% end %>

app/views/rents/_rent.html.erb
<p>
    Client:
    <%= rent.client %>
</p>
<p>
     Rent time:
    From <%= rent.from_date %> to <%= rent.to_date %>
</p>
<p>
    <% days = (rent.to_date - rent.from_date).to_i %>
    Days number: <%= days %> | 
    Rent price: <%= Price.where("comfort = ?", @car.comfort).uniq.pluck(:fare)[0] * days %>zł
</p>
<p>
    <%= link_to 'Delete rent', [rent.car, rent],
    method: :delete,
    data: { confirm: 'Are you sure?' } %>
</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
          <h2>Errors:</h2>
          <ul>
            <% object.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          </ul>
      <% end %>  
    </div>
  </div>
<% end %>  

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="center jumbotron">
  <h1>Welcome to Rental Cars</h1>
    

  <%= link_to "Sign in", new_user_session_path , class: "btn btn-lg btn-primary" %>
  <%= link_to "Sign up", new_user_registration_path , class: "btn btn-lg btn-primary" %>
</div>  